### ISSUE TITLE
Коментар по домашното

### ISSUE THREAD

**Issue by nkvelkov** [meftimova/object-oriented-programming#1]
Привет,

прегледах класовете от домашното. Като цяло си се справила много добре. Имам само някои дребни забележки. 

В класа String добре е да предефинираш String::operator[] по два начина: 
char& String::operator[](size_t index) и така
const char& String::operator[](size_t index)const

Причината да се налага да предефинираме и втората функция е, че когато извикваме оператора [] върху константа от тип String или върху константна референция към този тип, компилаторът няма да намери подходяща функция. Освен това понеже функцията трябва да е константна, т.е. не искаме да променяме член-данните, няма логика да връщаме само char& и затова трябва да върнем const char&.

В класа Student не е необходимо да предефинираш оператор =, тъй като класът няма данни разположени в динамичната памет. Ако не е предефиниран такъв оператор, компилаторът ще си създаде такъв и ще го извика и в този случай новосъздаденият оператор = ще има същото поведение, което ти си задала. 

В класа Group има член-данна разположена в динамичната памет, затова трябва да изтриеш текущото заетата памет в Group& Group::operator=(const Group& other) преди да извикаш функцията copy. Иначе това би довело до "изтичне" на памет. Във функцията addStudent трябва да освободиш паметта чак след като престанеш да я адресираш, т.е. функцията би следвало да придобие следния вид:

void Group::addStudent(const Student& student)
{
    if (size == capacity)
    {
        Student* temp = students;
        capacity *= 2;
        
        //delete [] students;

        students = new Student[capacity];

        for (size_t i = 0; i < size; i++)
            students[i] = temp[i];
       
        delete [] temp;
     }

    students[size] = student;
    size++;
}

Същото важи и за функцията copy. 
Като цяло това са забележките ми. Ако имаш някакви въпроси питай, извинявай че чак сега отговарям.

Поздрави,
Николай

**Comment by meftimova** [comment]
Здравей,

Благодаря за коментара. Всичко, което си посочил е вече fix-нато. :shipit:

**Comment by meftimova** [comment]
Здравей,

Преди да затворя issue-то, ако може да acknowledge-неш.

**Comment by nkvelkov** [comment]
Ok :)
